name: reptilearn2
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.10
  - pip:
    - flask
    - flask[async]
    - flask-cors
    - flask-socketio
    - imageio
    - imageio-ffmpeg
    - jupyter
    - numpy
    - opencv-python
    - paho-mqtt
    - pandas
    - pyserial
    - python-dotenv
    - Pillow
    - simple-websocket
    - psutil
    - requests
