name: reptilearn
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.8
  - tk=8.6.11
  - pip:
    - flask
    - flask-cors
    - flask-socketio
    - imageio
    - imageio-ffmpeg
    - jupyter
    - numpy
    - opencv-python
    - paho-mqtt
    - pandas
    - pyserial
    - python-dotenv

